"""fix: altera nome instituicoes para instituicao

Revision ID: 74e54a9c4447
Revises: 92b1b3e82158
Create Date: 2026-08-27 08:13:44.023915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e54a9c4447'
down_revision = '92b1b3e82158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instituicoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.String(), nullable=False))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('deficit_limit',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('deficit_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('instituicoes', schema=None) as batch_op:
        batch_op.drop_column('senha')

    # ### end Alembic commands ###
